import type { CGMPSemanticIconEntry } from "./types";

export const SEMANTIC_ICON_DICTIONARY_VERSION = "2026-06-07.2";
export const DEFAULT_SEMANTIC_ICON_THRESHOLD = 0.42;

const now = "2026-06-07T00:00:00.000Z";

export function createDefaultSemanticIconDictionary(): CGMPSemanticIconEntry[] {
  return [
    {
      key: "medical_dental",
      emoji: "🦷",
      label: "歯科",
      description: "歯医者、歯科、予約票、通院、デンタルケア。",
      keywords: ["歯医者", "歯科", "デンタル", "通院", "予約票"],
      examples: ["歯医者の予約", "歯科検診", "眼科予約票の確認"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "medical_hospital",
      emoji: "🏥",
      label: "医療",
      description: "病院、眼科、耳鼻科、薬、健康診断、医療関連の予定や記録。",
      keywords: ["病院", "眼科", "耳鼻科", "薬", "健康診断"],
      examples: ["眼科検査の予約詳細", "薬を受け取りに行く", "健康診断の結果確認"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "meeting",
      emoji: "👥",
      label: "会議",
      description: "会議、打ち合わせ、ミーティング、1on1、関係者との相談。",
      keywords: ["会議", "打合せ", "打ち合わせ", "ミーティング", "1on1", "相談"],
      examples: ["DNP様打ち合わせ", "森部長代理提案の傷検証資料確認", "矢田さんと磯本さんのコミュニケーション確認"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "communication",
      emoji: "💬",
      label: "連絡",
      description: "メール、電話、返信、送付、連絡、確認依頼。",
      keywords: ["メール", "電話", "返信", "送信", "送付", "連絡"],
      examples: ["小林のメールとDNPの状況整理", "棚卸し資料の西尾さんへの送付", "前田さんへ連絡"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "document",
      emoji: "📄",
      label: "資料",
      description: "資料、文書、レポート、議事録、報告書、仕様書。",
      keywords: ["資料", "文書", "レポート", "議事録", "報告書", "仕様書"],
      examples: ["品質ISO進捗記入", "PSC案件報告書確認", "資料準備"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "review_check",
      emoji: "🔍",
      label: "確認",
      description: "確認、レビュー、チェック、検証、調査、点検。",
      keywords: ["確認", "レビュー", "チェック", "検証", "調査", "点検"],
      examples: ["表面不良確認", "仕様確認", "Google Driveバックアップ確認"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "plan_strategy",
      emoji: "🧭",
      label: "計画",
      description: "計画、方針、整理、段取り、スケジュール設計、目標。",
      keywords: ["計画", "方針", "整理", "段取り", "目標", "予定"],
      examples: ["夏休み長野旅行計画の確定目標", "台風対策の確認", "今後の対応打ち合わせ"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "travel",
      emoji: "🧳",
      label: "旅行",
      description: "旅行、出張、ホテル、旅程、移動、予約。",
      keywords: ["旅行", "出張", "ホテル", "旅程", "移動", "予約"],
      examples: ["山城出張の報告督促", "長野旅行計画", "ホテル予約確認"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "shopping",
      emoji: "🛒",
      label: "買物",
      description: "購入、買い物、発注、準備物、日用品。",
      keywords: ["買う", "購入", "買い物", "発注", "準備"],
      examples: ["子供の自転車購入", "ホットケーキミックス購入", "財布と車の鍵の準備"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "finance",
      emoji: "💳",
      label: "お金",
      description: "支払い、精算、請求、費用、原価、経費、カード。",
      keywords: ["支払い", "精算", "請求", "費用", "原価", "経費", "カード"],
      examples: ["経理セミナー原価計算", "労務費資料送付", "支払い確認"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "family_child",
      emoji: "🧒",
      label: "子供",
      description: "子供、家族、学校、宿題、習い事、凜、瑛登。",
      keywords: ["子供", "家族", "学校", "宿題", "習い事", "凜", "瑛登"],
      examples: ["凜ちゃんの英語継続について", "久美子にシルバニアあげる予定", "子供の自転車購入"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "food",
      emoji: "🍽️",
      label: "食事",
      description: "食事、ご飯、弁当、ランチ、買い出し、献立。",
      keywords: ["食事", "ご飯", "弁当", "ランチ", "買い出し", "献立"],
      examples: ["晩御飯買い出し", "ランチ予定", "弁当準備"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "engineering",
      emoji: "💻",
      label: "開発",
      description: "実装、コード、PWA、Next.js、Vercel、Scriptable、Codex。",
      keywords: ["実装", "コード", "PWA", "Next.js", "Vercel", "Scriptable", "Codex"],
      examples: ["CGMP PWAのUI修正", "Webhookテスト", "Embedding検索機能"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "experiment_inspection",
      emoji: "🧪",
      label: "検査",
      description: "検査、試験、評価、実験、サンプル、測定、ISO。",
      keywords: ["検査", "試験", "評価", "実験", "サンプル", "測定", "ISO"],
      examples: ["X3サンプル表面不良確認", "NA3検査機サポート待機予定", "品質ISO進捗記入"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "factory",
      emoji: "🏭",
      label: "現場",
      description: "工場、生産、設備、現場、ライン、製造、加工。",
      keywords: ["工場", "生産", "設備", "現場", "ライン", "製造", "加工"],
      examples: ["AMAT向け生産キャパと納入スケジュール", "薄膜PSC試作の進め方", "設備仕様検討"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "delivery",
      emoji: "📦",
      label: "納入",
      description: "出荷、梱包、物流、納入、配送、送付。",
      keywords: ["出荷", "梱包", "物流", "納入", "配送", "送付"],
      examples: ["納入スケジュール確認", "棚卸し資料の送付", "出荷準備"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "deadline",
      emoji: "⏰",
      label: "期限",
      description: "締切、期限、督促、リマインド、提出。",
      keywords: ["締切", "期限", "督促", "リマインド", "提出"],
      examples: ["6/3の休暇予定提出", "報告督促", "資料提出期限"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "calendar_schedule",
      emoji: "📆",
      label: "日程",
      description: "日程、予定、スケジュール、予約、時間枠、カレンダー登録。",
      keywords: ["日程", "予定", "スケジュール", "予約", "時間枠", "カレンダー"],
      examples: ["6月2日の予定確認", "会議日程を登録", "予約時間の確認"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "task_todo",
      emoji: "☑️",
      label: "Todo",
      description: "タスク、やること、Todo、リマインダー、未完了作業。",
      keywords: ["タスク", "やること", "Todo", "リマインダー", "未完了"],
      examples: ["明日のタスク", "資料確認Todo", "完了にする"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "automation_sync",
      emoji: "🔄",
      label: "同期",
      description: "同期、バックアップ、アップロード、ダウンロード、復元、反映。",
      keywords: ["同期", "バックアップ", "アップロード", "ダウンロード", "復元", "反映"],
      examples: ["Google Drive同期確認", "Blobから復元", "全件再同期"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "cloud_drive",
      emoji: "☁️",
      label: "クラウド",
      description: "Google Drive、Vercel Blob、クラウド保存、オンラインストレージ。",
      keywords: ["Google Drive", "Drive", "Vercel Blob", "Blob", "クラウド", "保存先"],
      examples: ["Drive保存領域を変更", "Vercel Blob同期", "クラウドバックアップ"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "phone_shortcut",
      emoji: "📱",
      label: "iPhone",
      description: "iPhone、ショートカット、PWA、Safari、ホーム画面、モバイル操作。",
      keywords: ["iPhone", "ショートカット", "PWA", "Safari", "ホーム画面", "モバイル"],
      examples: ["iOS Shortcut webhook", "ホーム画面PWA更新", "iPhoneで写真追加"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "ai_prompt",
      emoji: "🤖",
      label: "AI",
      description: "AI解析、プロンプト、embedding、意味検索、画像解析。",
      keywords: ["AI", "プロンプト", "embedding", "意味検索", "画像解析", "OpenAI"],
      examples: ["AIプロンプト編集", "semantic icon辞書", "画像AI解析"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "search_find",
      emoji: "🔎",
      label: "検索",
      description: "検索、フィルター、絞り込み、一覧、見つける、探す。",
      keywords: ["検索", "フィルター", "絞り込み", "一覧", "探す", "見つける"],
      examples: ["domainフィルター", "意味検索", "タグ検索"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "bug_fix",
      emoji: "🐞",
      label: "不具合",
      description: "バグ、不具合、エラー、失敗、修正、原因調査。",
      keywords: ["バグ", "不具合", "エラー", "失敗", "修正", "原因"],
      examples: ["削除時のIndexedDBエラー", "同期が失敗", "表示崩れ修正"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "ui_design",
      emoji: "🎨",
      label: "UI",
      description: "UI、デザイン、レイアウト、見た目、モーダル、アニメーション。",
      keywords: ["UI", "デザイン", "レイアウト", "モーダル", "アニメーション", "見た目"],
      examples: ["Today viewのUI調整", "カードの余白", "ミニマップ表示"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "settings_config",
      emoji: "⚙️",
      label: "設定",
      description: "設定、環境変数、Preferences、テーマ、閾値、構成変更。",
      keywords: ["設定", "環境変数", "テーマ", "閾値", "構成", "Preferences"],
      examples: ["Settings画面整理", "semantic icon閾値", "環境変数追加"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "import_export",
      emoji: "📥",
      label: "移行",
      description: "インポート、エクスポート、移行、zip、Scriptableデータ取り込み。",
      keywords: ["インポート", "エクスポート", "移行", "zip", "Scriptable", "取り込み"],
      examples: ["Scriptableログ移行", "zipアップロード", "データ移行"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "delete_archive",
      emoji: "🗑️",
      label: "削除",
      description: "削除、アーカイブ、tombstone、消す、復活防止。",
      keywords: ["削除", "アーカイブ", "tombstone", "消す", "復活", "全削除"],
      examples: ["メモ削除の挙動", "Drive tombstone", "選択削除"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "backup_restore",
      emoji: "🧰",
      label: "保守",
      description: "保守、復元、再構築、リカバリ、バックアップ検証。",
      keywords: ["保守", "復元", "再構築", "リカバリ", "検証", "復旧"],
      examples: ["画像復元", "index再構築", "Drive実在確認"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "weather_disaster",
      emoji: "🌪️",
      label: "災害",
      description: "台風、雨、雪、災害、停電、防災、天気。",
      keywords: ["台風", "雨", "雪", "災害", "停電", "防災", "天気"],
      examples: ["台風対策の確認", "雪国だった", "天気の影響確認"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "car_transport",
      emoji: "🚗",
      label: "移動",
      description: "車、電車、交通、移動、駐車場、運転、充電。",
      keywords: ["車", "電車", "交通", "移動", "駐車場", "運転", "充電"],
      examples: ["電気自動車充電ケーブル", "車の鍵", "移動予定"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "home_house",
      emoji: "🏠",
      label: "家庭",
      description: "家、家庭、住まい、家事、生活、家族内の用事。",
      keywords: ["家", "家庭", "住まい", "家事", "生活", "自宅"],
      examples: ["家の片付け", "家庭の予定", "生活管理"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "cleaning",
      emoji: "🧹",
      label: "掃除",
      description: "掃除、片付け、整理整頓、ゴミ、清掃。",
      keywords: ["掃除", "片付け", "整理整頓", "ゴミ", "清掃"],
      examples: ["外ゴミ階段", "片付ける", "掃除予定"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "clothes_laundry",
      emoji: "👕",
      label: "衣類",
      description: "服、洗濯、衣類、サイズ、靴、身支度。",
      keywords: ["服", "洗濯", "衣類", "サイズ", "靴", "身支度"],
      examples: ["サイズ140cmの服", "洗濯", "服の購入計画"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "pet_animal",
      emoji: "🐾",
      label: "動物",
      description: "ペット、動物、生き物、魚、飼育、観察。",
      keywords: ["ペット", "動物", "生き物", "魚", "飼育", "観察"],
      examples: ["手に乗った生き物の写真", "魚の世話", "動物観察"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "education_learning",
      emoji: "📚",
      label: "学習",
      description: "学習、勉強、英語、セミナー、講座、教育。",
      keywords: ["学習", "勉強", "英語", "セミナー", "講座", "教育"],
      examples: ["凜ちゃんの英語継続", "経理セミナー", "学習計画"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "book_reading",
      emoji: "📖",
      label: "読書",
      description: "本、読書、資料読み、参考文献、記事。",
      keywords: ["本", "読書", "参考文献", "記事", "読み物"],
      examples: ["参考資料を読む", "記事確認", "本のメモ"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "legal_contract",
      emoji: "📝",
      label: "契約",
      description: "契約、規約、許可、申請、承認、法務系の確認。",
      keywords: ["契約", "規約", "許可", "申請", "承認", "法務"],
      examples: ["シルバニアをあげる許可", "申請書確認", "承認事項"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "security_password",
      emoji: "🔐",
      label: "認証",
      description: "認証、ログイン、OAuth、token、API key、権限。",
      keywords: ["認証", "ログイン", "OAuth", "token", "API key", "権限"],
      examples: ["Google OAuth設定", "Webhook token", "環境変数登録"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "energy_electricity",
      emoji: "🔌",
      label: "電気",
      description: "電気、充電、電源、ケーブル、バッテリー、設備電源。",
      keywords: ["電気", "充電", "電源", "ケーブル", "バッテリー", "EV"],
      examples: ["電気自動車充電ケーブル", "電源確認", "バッテリー"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "measurement_size",
      emoji: "📏",
      label: "寸法",
      description: "サイズ、寸法、測定、長さ、厚み、mm、座標。",
      keywords: ["サイズ", "寸法", "測定", "長さ", "厚み", "mm", "座標"],
      examples: ["72.5-120mmガラス基板サイズ", "二次元座標測定器", "15x2セット"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "material_glass",
      emoji: "🧊",
      label: "材料",
      description: "ガラス、薄膜、基板、材料、サンプル、表面。",
      keywords: ["ガラス", "薄膜", "基板", "材料", "サンプル", "表面"],
      examples: ["DNPガラスサイズ", "薄膜PSC", "X3サンプル表面不良"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "customer_sales",
      emoji: "🤝",
      label: "顧客",
      description: "顧客、取引先、先方、営業、依頼、提案。",
      keywords: ["顧客", "取引先", "先方", "営業", "依頼", "提案"],
      examples: ["DNP様打ち合わせ", "AMAT向け", "お客様への伝達"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "quality_iso",
      emoji: "🏷️",
      label: "品質",
      description: "品質、ISO、不良、検査結果、是正、監査。",
      keywords: ["品質", "ISO", "不良", "検査結果", "是正", "監査"],
      examples: ["品質ISO進捗記入", "表面不良確認", "品質報告"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "procurement",
      emoji: "🧾",
      label: "購買",
      description: "見積、購買、発注、請求書、領収書、伝票。",
      keywords: ["見積", "購買", "発注", "請求書", "領収書", "伝票"],
      examples: ["検査機見積もり作業", "発注準備", "領収書画像"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "maintenance_repair",
      emoji: "🛠️",
      label: "修理",
      description: "修理、メンテナンス、設備保全、調整、再起動、対応。",
      keywords: ["修理", "メンテナンス", "設備保全", "調整", "再起動", "対応"],
      examples: ["検査機の再起動ループ対策", "設備メンテ", "調整作業"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "inventory_stock",
      emoji: "📊",
      label: "在庫",
      description: "在庫、棚卸し、数量、入荷、出荷、残数。",
      keywords: ["在庫", "棚卸し", "数量", "入荷", "出荷", "残数"],
      examples: ["棚卸し資料", "30枚", "在庫確認"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "ticket_receipt",
      emoji: "🎫",
      label: "券",
      description: "予約票、チケット、領収書、レシート、受付票。",
      keywords: ["予約票", "チケット", "領収書", "レシート", "受付票"],
      examples: ["眼科検査の予約票", "領収書写真", "受付票確認"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "map_location",
      emoji: "📍",
      label: "場所",
      description: "場所、住所、訪問先、現地、地図、会場。",
      keywords: ["場所", "住所", "訪問先", "現地", "地図", "会場"],
      examples: ["訪問先確認", "会場の場所", "現地集合"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "event_ceremony",
      emoji: "🎉",
      label: "行事",
      description: "イベント、行事、式、発表会、記念日、参加予定。",
      keywords: ["イベント", "行事", "式", "発表会", "記念日", "参加"],
      examples: ["学校行事", "イベント参加", "発表会予定"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "rest_sleep",
      emoji: "🌙",
      label: "休息",
      description: "休み、休暇、睡眠、体調回復、夜、集中タイム。",
      keywords: ["休み", "休暇", "睡眠", "体調", "夜", "集中"],
      examples: ["6/3の休暇予定提出", "夜の集中タイム", "体調を整える"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "exercise_health",
      emoji: "🏃",
      label: "運動",
      description: "運動、散歩、トレーニング、体力、健康習慣。",
      keywords: ["運動", "散歩", "トレーニング", "体力", "健康習慣"],
      examples: ["散歩する", "運動予定", "体力づくり"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "garden_outdoor",
      emoji: "🌿",
      label: "屋外",
      description: "屋外、庭、外作業、自然、植物、外出先の観察。",
      keywords: ["屋外", "庭", "外作業", "自然", "植物", "外出"],
      examples: ["外での作業", "自然観察", "庭の確認"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "idea",
      emoji: "💡",
      label: "発想",
      description: "アイデア、構想、考える、改善案、発明、仮説。",
      keywords: ["アイデア", "構想", "考える", "改善", "仮説"],
      examples: ["UIの改善案", "プロンプト設計", "検索体験の改善"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "image_photo",
      emoji: "🖼️",
      label: "画像",
      description: "写真、スクリーンショット、画像、添付、カメラ、撮影。",
      keywords: ["写真", "スクリーンショット", "画像", "添付", "カメラ", "撮影"],
      examples: ["DNP様強化依頼詳細スクリーンショット", "写真を追加", "画面キャプチャ確認"],
      enabled: true,
      updated_at: now,
    },
  ];
}
