import type { CGMPSemanticIconEntry } from "./types";

export const SEMANTIC_ICON_DICTIONARY_VERSION = "2026-06-07.3";
export const DEFAULT_SEMANTIC_ICON_THRESHOLD = 0.42;

const now = "2026-06-07T00:00:00.000Z";

type SemanticIconSeed = Omit<CGMPSemanticIconEntry, "enabled" | "updated_at">;

function createEntry(seed: SemanticIconSeed): CGMPSemanticIconEntry {
  return {
    ...seed,
    enabled: true,
    updated_at: now,
  };
}

const EXTENDED_SEMANTIC_ICON_SEEDS: SemanticIconSeed[] = [
  {
    key: "music_piano",
    emoji: "🎹",
    label: "ピアノ",
    description: "ピアノ、鍵盤、演奏、練習、発表会、音楽レッスン。",
    keywords: ["ピアノ", "鍵盤", "演奏", "練習", "発表会", "音楽"],
    examples: ["凜ちゃんピアノアンサンブル練習", "ピアノ発表会の予定", "鍵盤練習"],
  },
  {
    key: "music_lesson",
    emoji: "🎼",
    label: "音楽",
    description: "音楽、合奏、アンサンブル、レッスン、楽譜、歌。",
    keywords: ["音楽", "合奏", "アンサンブル", "レッスン", "楽譜", "歌"],
    examples: ["アンサンブル練習", "音楽教室", "楽譜を確認"],
  },
  {
    key: "haircut_beauty",
    emoji: "💇",
    label: "ヘアカット",
    description: "ヘアカット、散髪、美容院、床屋、髪、カット予約。",
    keywords: ["ヘアカット", "散髪", "美容院", "床屋", "髪", "カット"],
    examples: ["久美子へヘアカットの予定", "美容院予約", "髪を切る"],
  },
  {
    key: "pizza_food",
    emoji: "🍕",
    label: "ピザ",
    description: "ピザ、チーズ、焼く、ランチ、昼食、軽食。",
    keywords: ["ピザ", "チーズ", "焼く", "ランチ", "昼食", "軽食"],
    examples: ["ピザ焼き予定", "日曜日昼ピザ焼き", "ランチの準備"],
  },
  {
    key: "cooking_recipe",
    emoji: "🍳",
    label: "料理",
    description: "料理、レシピ、調理、献立、材料、作り方。",
    keywords: ["料理", "レシピ", "調理", "献立", "材料", "作り方"],
    examples: ["酒蒸しハンバーグのレシピ", "晩ご飯の献立", "材料を準備"],
  },
  {
    key: "restaurant_meal",
    emoji: "🍜",
    label: "外食",
    description: "外食、店、レストラン、昼ご飯、夕食、食べに行く。",
    keywords: ["外食", "店", "レストラン", "昼ご飯", "夕食", "食べに行く"],
    examples: ["ランチに行く", "夕食の店を予約", "家族で外食"],
  },
  {
    key: "school",
    emoji: "🏫",
    label: "学校",
    description: "学校、小学校、授業、先生、登校、学用品。",
    keywords: ["学校", "小学校", "授業", "先生", "登校", "学用品"],
    examples: ["学校行事の確認", "先生への連絡", "登校準備"],
  },
  {
    key: "kindergarten",
    emoji: "🎒",
    label: "園",
    description: "幼稚園、保育園、園、送迎、持ち物。",
    keywords: ["幼稚園", "保育園", "園", "送迎", "持ち物"],
    examples: ["保育園の持ち物", "園への送迎", "幼稚園行事"],
  },
  {
    key: "homework",
    emoji: "✏️",
    label: "宿題",
    description: "宿題、課題、プリント、提出物、勉強の確認。",
    keywords: ["宿題", "課題", "プリント", "提出物", "勉強"],
    examples: ["凜の宿題を見る", "プリント確認", "課題提出"],
  },
  {
    key: "exam_test",
    emoji: "🧠",
    label: "試験",
    description: "試験、テスト、模試、採点、合格、勉強計画。",
    keywords: ["試験", "テスト", "模試", "採点", "合格", "受験"],
    examples: ["テスト勉強", "模試の予定", "試験結果確認"],
  },
  {
    key: "child_activity",
    emoji: "🛝",
    label: "子供予定",
    description: "子供の予定、遊び、習い事、送迎、家族イベント。",
    keywords: ["子供", "遊び", "習い事", "送迎", "家族イベント"],
    examples: ["子供の習い事", "公園に行く", "送迎予定"],
  },
  {
    key: "gift_present",
    emoji: "🎁",
    label: "贈り物",
    description: "プレゼント、贈り物、お祝い、渡す、ギフト。",
    keywords: ["プレゼント", "贈り物", "お祝い", "渡す", "ギフト"],
    examples: ["久美子にシルバニアをあげる", "誕生日プレゼント", "お祝いを渡す"],
  },
  {
    key: "bicycle",
    emoji: "🚲",
    label: "自転車",
    description: "自転車、サイクル、サイズ、ヘルメット、購入。",
    keywords: ["自転車", "サイクル", "ヘルメット", "インチ", "サイズ"],
    examples: ["子供の自転車購入", "21インチ自転車", "ヘルメット確認"],
  },
  {
    key: "toy_play",
    emoji: "🧸",
    label: "おもちゃ",
    description: "おもちゃ、シルバニア、遊び道具、ゲーム、子供用品。",
    keywords: ["おもちゃ", "シルバニア", "遊び道具", "ゲーム", "子供用品"],
    examples: ["シルバニアを渡す", "おもちゃ整理", "子供用品購入"],
  },
  {
    key: "weekend_plan",
    emoji: "🌤️",
    label: "週末",
    description: "週末、土日、休日、休みの日の予定。",
    keywords: ["週末", "土日", "休日", "日曜日", "土曜日"],
    examples: ["日曜日昼ピザ焼き", "週末の予定", "休日に買い物"],
  },
  {
    key: "birthday_anniversary",
    emoji: "🎂",
    label: "記念日",
    description: "誕生日、記念日、お祝い、ケーキ、プレゼント。",
    keywords: ["誕生日", "記念日", "お祝い", "ケーキ", "プレゼント"],
    examples: ["誕生日ケーキ", "記念日の予定", "お祝い準備"],
  },
  {
    key: "medical_eye",
    emoji: "👁️",
    label: "眼科",
    description: "眼科、視力、目、検眼、予約票、診察。",
    keywords: ["眼科", "視力", "目", "検眼", "予約票", "診察"],
    examples: ["瑛ちゃん眼科予定と診察メモ", "眼科検査予約票", "視力検査"],
  },
  {
    key: "medical_ear",
    emoji: "👂",
    label: "耳鼻科",
    description: "耳鼻科、耳、鼻、喉、診察、通院。",
    keywords: ["耳鼻科", "耳", "鼻", "喉", "診察", "通院"],
    examples: ["耳鼻科へ行く", "鼻の診察", "喉の薬"],
  },
  {
    key: "medical_medicine",
    emoji: "💊",
    label: "薬",
    description: "薬、処方、服薬、薬局、受け取り、投薬。",
    keywords: ["薬", "処方", "服薬", "薬局", "受け取り", "投薬"],
    examples: ["薬を受け取る", "処方箋確認", "服薬メモ"],
  },
  {
    key: "medical_checkup",
    emoji: "🩺",
    label: "健診",
    description: "健康診断、検診、体調、通院、検査結果。",
    keywords: ["健康診断", "検診", "体調", "通院", "検査結果"],
    examples: ["健康診断の予定", "検診結果確認", "体調メモ"],
  },
  {
    key: "dental_orthodontic",
    emoji: "🪥",
    label: "歯ケア",
    description: "歯磨き、矯正、虫歯、歯科ケア、予約。",
    keywords: ["歯磨き", "矯正", "虫歯", "歯科ケア", "歯医者"],
    examples: ["歯科矯正相談", "虫歯の確認", "歯磨き用品"],
  },
  {
    key: "sleep_bedtime",
    emoji: "🛌",
    label: "睡眠",
    description: "睡眠、就寝、寝る、起床、休息、夜。",
    keywords: ["睡眠", "就寝", "寝る", "起床", "休息", "夜"],
    examples: ["早く寝る", "睡眠時間メモ", "起床予定"],
  },
  {
    key: "mental_focus",
    emoji: "🧘",
    label: "集中",
    description: "集中、メンタル、気分、考え事、落ち着く。",
    keywords: ["集中", "メンタル", "気分", "考え事", "落ち着く"],
    examples: ["夜の集中タイム", "気分の記録", "考え事メモ"],
  },
  {
    key: "exercise_walk",
    emoji: "🚶",
    label: "散歩",
    description: "散歩、歩く、ウォーキング、運動、外出。",
    keywords: ["散歩", "歩く", "ウォーキング", "運動", "外出"],
    examples: ["散歩に行く", "ウォーキング", "外に出る"],
  },
  {
    key: "weight_health",
    emoji: "⚖️",
    label: "体重",
    description: "体重、健康管理、食事制限、ダイエット、記録。",
    keywords: ["体重", "健康管理", "食事制限", "ダイエット", "記録"],
    examples: ["体重を記録", "健康管理メモ", "食事制限"],
  },
  {
    key: "car_ev",
    emoji: "🔋",
    label: "EV",
    description: "電気自動車、EV、充電、充電ケーブル、バッテリー。",
    keywords: ["電気自動車", "EV", "充電", "充電ケーブル", "バッテリー"],
    examples: ["電気自動車充電ケーブル", "EV充電予定", "バッテリー確認"],
  },
  {
    key: "car_maintenance",
    emoji: "🔧",
    label: "車整備",
    description: "車検、点検、整備、タイヤ、修理、車用品。",
    keywords: ["車検", "点検", "整備", "タイヤ", "修理", "車用品"],
    examples: ["車の点検", "タイヤ交換", "車用品購入"],
  },
  {
    key: "train_commute",
    emoji: "🚆",
    label: "電車",
    description: "電車、駅、通勤、乗換、交通機関。",
    keywords: ["電車", "駅", "通勤", "乗換", "交通機関"],
    examples: ["電車の時間確認", "駅で待ち合わせ", "乗換確認"],
  },
  {
    key: "parking",
    emoji: "🅿️",
    label: "駐車",
    description: "駐車場、駐車、車を停める、パーキング。",
    keywords: ["駐車場", "駐車", "停める", "パーキング"],
    examples: ["駐車場確認", "車を停める場所", "パーキング料金"],
  },
  {
    key: "travel_hotel",
    emoji: "🏨",
    label: "ホテル",
    description: "ホテル、宿泊、旅館、チェックイン、予約。",
    keywords: ["ホテル", "宿泊", "旅館", "チェックイン", "予約"],
    examples: ["ホテル予約確認", "宿泊先", "チェックイン時間"],
  },
  {
    key: "travel_ticket",
    emoji: "🎟️",
    label: "切符",
    description: "切符、航空券、チケット、乗車券、予約番号。",
    keywords: ["切符", "航空券", "チケット", "乗車券", "予約番号"],
    examples: ["新幹線チケット", "航空券確認", "乗車券購入"],
  },
  {
    key: "packing",
    emoji: "🧳",
    label: "荷造り",
    description: "荷造り、持ち物、準備物、旅行準備、忘れ物。",
    keywords: ["荷造り", "持ち物", "準備物", "旅行準備", "忘れ物"],
    examples: ["旅行の持ち物", "荷造りリスト", "忘れ物確認"],
  },
  {
    key: "map_route",
    emoji: "🗺️",
    label: "経路",
    description: "経路、地図、ルート、道順、所要時間。",
    keywords: ["経路", "地図", "ルート", "道順", "所要時間"],
    examples: ["会場までのルート", "地図確認", "所要時間を調べる"],
  },
  {
    key: "weather_typhoon",
    emoji: "🌀",
    label: "台風",
    description: "台風、暴風、雨風、警報、天候対策。",
    keywords: ["台風", "暴風", "雨風", "警報", "天候"],
    examples: ["6月2日の台風対策", "台風対策の確認", "警報確認"],
  },
  {
    key: "weather_heat",
    emoji: "🥵",
    label: "暑さ",
    description: "暑さ、熱中症、気温、猛暑、水分補給。",
    keywords: ["暑さ", "熱中症", "気温", "猛暑", "水分補給"],
    examples: ["熱中症対策", "暑さ対策", "水分補給"],
  },
  {
    key: "disaster_preparedness",
    emoji: "🎒",
    label: "防災",
    description: "防災、備蓄、避難、災害対策、非常用品。",
    keywords: ["防災", "備蓄", "避難", "災害対策", "非常用品"],
    examples: ["防災用品確認", "避難経路", "備蓄の確認"],
  },
  {
    key: "home_repair",
    emoji: "🏚️",
    label: "家修理",
    description: "家の修理、補修、設備、ドア、壁、修繕。",
    keywords: ["家の修理", "補修", "設備", "ドア", "壁", "修繕"],
    examples: ["家の設備修理", "ドアの調整", "壁の補修"],
  },
  {
    key: "home_appliance",
    emoji: "🧺",
    label: "家電",
    description: "家電、洗濯機、冷蔵庫、エアコン、掃除機。",
    keywords: ["家電", "洗濯機", "冷蔵庫", "エアコン", "掃除機"],
    examples: ["エアコン確認", "冷蔵庫整理", "洗濯機の調子"],
  },
  {
    key: "trash_recycling",
    emoji: "♻️",
    label: "ゴミ",
    description: "ゴミ、資源ごみ、リサイクル、分別、回収。",
    keywords: ["ゴミ", "資源ごみ", "リサイクル", "分別", "回収"],
    examples: ["外ゴミ階段", "自転車回収の予定", "分別する"],
  },
  {
    key: "laundry_wash",
    emoji: "🧦",
    label: "洗濯",
    description: "洗濯、干す、畳む、衣類、タオル。",
    keywords: ["洗濯", "干す", "畳む", "衣類", "タオル"],
    examples: ["洗濯物を干す", "衣類を畳む", "タオル準備"],
  },
  {
    key: "shopping_grocery",
    emoji: "🥬",
    label: "食材",
    description: "食材、スーパー、買い出し、野菜、食品。",
    keywords: ["食材", "スーパー", "買い出し", "野菜", "食品"],
    examples: ["晩御飯買い出し", "スーパーで食材購入", "野菜を買う"],
  },
  {
    key: "shopping_clothes",
    emoji: "👚",
    label: "服購入",
    description: "服、衣類、サイズ、購入、子供服。",
    keywords: ["服", "衣類", "サイズ", "購入", "子供服"],
    examples: ["服の購入計画", "サイズ140cm", "子供服を買う"],
  },
  {
    key: "shopping_online",
    emoji: "📦",
    label: "通販",
    description: "通販、Amazon、楽天、注文、配送、荷物。",
    keywords: ["通販", "Amazon", "楽天", "注文", "配送", "荷物"],
    examples: ["Amazon注文", "配送状況確認", "荷物受け取り"],
  },
  {
    key: "money_payment",
    emoji: "💸",
    label: "支払",
    description: "支払い、振込、精算、料金、会計。",
    keywords: ["支払い", "振込", "精算", "料金", "会計"],
    examples: ["料金支払い", "振込確認", "精算する"],
  },
  {
    key: "money_budget",
    emoji: "📒",
    label: "予算",
    description: "予算、家計、費用計画、節約、収支。",
    keywords: ["予算", "家計", "費用計画", "節約", "収支"],
    examples: ["旅行予算", "家計の確認", "費用計画"],
  },
  {
    key: "money_tax",
    emoji: "🧮",
    label: "税金",
    description: "税金、確定申告、年末調整、控除、納税。",
    keywords: ["税金", "確定申告", "年末調整", "控除", "納税"],
    examples: ["税金確認", "確定申告資料", "年末調整"],
  },
  {
    key: "insurance",
    emoji: "🛡️",
    label: "保険",
    description: "保険、契約、補償、保険証、更新。",
    keywords: ["保険", "契約", "補償", "保険証", "更新"],
    examples: ["保険内容確認", "保険証", "契約更新"],
  },
  {
    key: "bank_account",
    emoji: "🏦",
    label: "銀行",
    description: "銀行、口座、残高、振込、通帳。",
    keywords: ["銀行", "口座", "残高", "振込", "通帳"],
    examples: ["口座残高確認", "銀行振込", "通帳記帳"],
  },
  {
    key: "work_report",
    emoji: "📋",
    label: "報告",
    description: "報告、レポート、進捗、状況共有、結果記入。",
    keywords: ["報告", "レポート", "進捗", "状況共有", "結果"],
    examples: ["品質ISO進捗記入", "報告書確認", "進捗共有"],
  },
  {
    key: "work_customer_dnp",
    emoji: "🏢",
    label: "DNP",
    description: "DNP、DNP様、DNP案件、取引先対応。",
    keywords: ["DNP", "DNP様", "DNP案件"],
    examples: ["DNP様打ち合わせ", "DNPガラスサイズ", "DNP案件確認"],
  },
  {
    key: "work_customer_amat",
    emoji: "🏭",
    label: "AMAT",
    description: "AMAT、AMAT向け、生産キャパ、納入スケジュール。",
    keywords: ["AMAT", "AMAT向け", "生産キャパ", "納入"],
    examples: ["AMAT向け生産キャパと納入スケジュール", "AMAT打ち合わせ"],
  },
  {
    key: "work_customer_negt",
    emoji: "🏗️",
    label: "NEGT",
    description: "NEGT案件、NEGT、客先対応、傷検証。",
    keywords: ["NEGT", "NEGT案件", "傷検証"],
    examples: ["山城とNEGT案件今後の対応打ち合わせ", "NEGT傷サンプル"],
  },
  {
    key: "work_customer_psc",
    emoji: "🧫",
    label: "PSC",
    description: "PSC案件、薄膜PSC、試作、設備仕様、コーティング。",
    keywords: ["PSC", "薄膜PSC", "試作", "設備仕様", "コーティング"],
    examples: ["薄膜PSC試作の進め方", "矢田依頼のPSC案件設備仕様検討"],
  },
  {
    key: "work_customer_jpn",
    emoji: "🗾",
    label: "JPN",
    description: "JPN、JPNデータ、国内案件、顧客資料。",
    keywords: ["JPN", "JPNデータ", "国内案件"],
    examples: ["JPNデータまとめ", "JPN資料確認"],
  },
  {
    key: "work_quote",
    emoji: "💹",
    label: "見積",
    description: "見積、見積もり、価格、費用算出、金額。",
    keywords: ["見積", "見積もり", "価格", "費用算出", "金額"],
    examples: ["検査機見積もり作業メモ", "見積金額を算出", "価格確認"],
  },
  {
    key: "work_invoice",
    emoji: "🧾",
    label: "請求",
    description: "請求書、納品書、領収書、伝票、経理書類。",
    keywords: ["請求書", "納品書", "領収書", "伝票", "経理書類"],
    examples: ["領収書写真", "請求書確認", "納品書作成"],
  },
  {
    key: "work_delivery_date",
    emoji: "🚚",
    label: "納期",
    description: "納期、納入、出荷日、納入スケジュール、配送。",
    keywords: ["納期", "納入", "出荷日", "納入スケジュール", "配送"],
    examples: ["納入スケジュール確認", "出荷日の調整", "納期回答"],
  },
  {
    key: "work_production_capacity",
    emoji: "🏭",
    label: "生産",
    description: "生産、キャパ、生産能力、工程、ライン、製造計画。",
    keywords: ["生産", "キャパ", "生産能力", "工程", "ライン", "製造計画"],
    examples: ["生産キャパ確認", "工程調整", "製造計画"],
  },
  {
    key: "work_material_procurement",
    emoji: "🏗️",
    label: "部材",
    description: "部材、材料、母材、購買、入手、調達。",
    keywords: ["部材", "材料", "母材", "購買", "入手", "調達"],
    examples: ["母材の内部欠陥", "部材調達", "材料確認"],
  },
  {
    key: "work_quality_issue",
    emoji: "⚠️",
    label: "品質問題",
    description: "品質問題、不良、傷、欠陥、クレーム、異常。",
    keywords: ["品質問題", "不良", "傷", "欠陥", "クレーム", "異常"],
    examples: ["表面不良確認", "傷検証資料", "欠陥の歩留まり"],
  },
  {
    key: "work_iso_audit",
    emoji: "📌",
    label: "ISO",
    description: "ISO、監査、品質規格、文書レビュー、進捗記入。",
    keywords: ["ISO", "監査", "品質規格", "文書レビュー", "進捗記入"],
    examples: ["品質ISO進捗記入", "ISO文書レビュー", "監査準備"],
  },
  {
    key: "work_safety",
    emoji: "⛑️",
    label: "安全",
    description: "安全、KY、労災、危険予知、保護具、注意事項。",
    keywords: ["安全", "KY", "労災", "危険予知", "保護具", "注意事項"],
    examples: ["安全確認", "保護具準備", "注意事項を記録"],
  },
  {
    key: "work_training",
    emoji: "🎓",
    label: "教育",
    description: "研修、教育、トレーニング、講習、訓練。",
    keywords: ["研修", "教育", "トレーニング", "講習", "訓練"],
    examples: ["三成さんへの訓練不参加の連絡", "研修予定", "教育資料"],
  },
  {
    key: "work_hr_labor",
    emoji: "👷",
    label: "労務",
    description: "労務、人事、勤怠、休暇、労務費、申請。",
    keywords: ["労務", "人事", "勤怠", "休暇", "労務費", "申請"],
    examples: ["労務費資料送付", "休暇予定提出", "勤怠確認"],
  },
  {
    key: "work_accounting_cost",
    emoji: "🧮",
    label: "原価",
    description: "原価、経理、会計、コスト、計算、収支。",
    keywords: ["原価", "経理", "会計", "コスト", "計算", "収支"],
    examples: ["経理セミナー原価計算", "コスト確認", "原価計算"],
  },
  {
    key: "work_meeting_minutes",
    emoji: "🗒️",
    label: "議事録",
    description: "議事録、会議メモ、打ち合わせ内容、決定事項。",
    keywords: ["議事録", "会議メモ", "打ち合わせ内容", "決定事項"],
    examples: ["PTAの議事録作成", "会議メモ整理", "決定事項記録"],
  },
  {
    key: "work_email_followup",
    emoji: "📧",
    label: "メール",
    description: "メール、返信、フォロー、連絡、送信、CC。",
    keywords: ["メール", "返信", "フォロー", "連絡", "送信", "CC"],
    examples: ["小林のメールとDNPの状況整理", "メール返信", "連絡フォロー"],
  },
  {
    key: "work_presentation",
    emoji: "📊",
    label: "発表資料",
    description: "プレゼン、スライド、発表資料、説明資料、報告会。",
    keywords: ["プレゼン", "スライド", "発表資料", "説明資料", "報告会"],
    examples: ["説明資料を作る", "報告会スライド", "プレゼン準備"],
  },
  {
    key: "work_negotiation",
    emoji: "🤝",
    label: "調整",
    description: "交渉、調整、相談、依頼、合意、すり合わせ。",
    keywords: ["交渉", "調整", "相談", "依頼", "合意", "すり合わせ"],
    examples: ["関係者役割の確認", "お客様と調整", "依頼内容相談"],
  },
  {
    key: "work_contract_review",
    emoji: "📑",
    label: "契約確認",
    description: "契約、仕様書、規約、注文書、合意条件、確認。",
    keywords: ["契約", "仕様書", "規約", "注文書", "合意条件"],
    examples: ["設備仕様確認", "注文書確認", "契約条件レビュー"],
  },
  {
    key: "work_schedule_adjustment",
    emoji: "🗓️",
    label: "日程調整",
    description: "日程調整、スケジュール確認、予定変更、時間調整。",
    keywords: ["日程調整", "スケジュール確認", "予定変更", "時間調整"],
    examples: ["納入スケジュール調整", "打ち合わせ日程", "予定変更"],
  },
  {
    key: "work_equipment_spec",
    emoji: "⚙️",
    label: "設備仕様",
    description: "設備、仕様、装置、機械、仕様検討、要件。",
    keywords: ["設備", "仕様", "装置", "機械", "仕様検討", "要件"],
    examples: ["PSC案件設備仕様検討", "検査機仕様", "装置要件"],
  },
  {
    key: "work_machine_inspection",
    emoji: "🔬",
    label: "検査機",
    description: "検査機、測定器、装置、サポート、点検、検査設備。",
    keywords: ["検査機", "測定器", "装置", "サポート", "点検", "検査設備"],
    examples: ["NA3検査機サポート待機予定", "二次元座標測定器", "検査機見積もり"],
  },
  {
    key: "work_measurement_coordinate",
    emoji: "📐",
    label: "測定",
    description: "測定、座標、寸法、計測、評価、測定器。",
    keywords: ["測定", "座標", "寸法", "計測", "評価", "測定器"],
    examples: ["二次元座標測定器", "サイズ測定", "寸法確認"],
  },
  {
    key: "work_surface_defect",
    emoji: "🔎",
    label: "表面不良",
    description: "表面不良、傷、欠陥、異物、外観、検証。",
    keywords: ["表面不良", "傷", "欠陥", "異物", "外観", "検証"],
    examples: ["X3サンプル表面不良確認", "傷検証", "外観確認"],
  },
  {
    key: "work_glass_substrate",
    emoji: "🪟",
    label: "ガラス",
    description: "ガラス、基板、板、サイズ、厚み、薄膜。",
    keywords: ["ガラス", "基板", "板", "サイズ", "厚み", "薄膜"],
    examples: ["72.5-120mm DNP案件ガラス基板サイズ", "DNPガラスサイズ"],
  },
  {
    key: "work_thinfilm",
    emoji: "🌈",
    label: "薄膜",
    description: "薄膜、成膜、膜、PSC、コーティング、試作。",
    keywords: ["薄膜", "成膜", "膜", "PSC", "コーティング", "試作"],
    examples: ["薄膜PSC試作", "成膜不可", "コーティング方針"],
  },
  {
    key: "work_sample_flow",
    emoji: "🧪",
    label: "流動",
    description: "サンプル、流動、試作、評価、条件確認。",
    keywords: ["サンプル", "流動", "試作", "評価", "条件確認"],
    examples: ["NEGT傷サンプル流動", "小型強化サンプル", "試作評価"],
  },
  {
    key: "work_reboot_issue",
    emoji: "🔁",
    label: "再起動",
    description: "再起動、ループ、システム異常、復旧、障害対応。",
    keywords: ["再起動", "ループ", "システム異常", "復旧", "障害"],
    examples: ["検査機の再起動ループ対策", "システム復旧", "障害対応"],
  },
  {
    key: "work_inventory_count",
    emoji: "📦",
    label: "棚卸",
    description: "棚卸し、在庫、数量、カウント、残数、入出庫。",
    keywords: ["棚卸し", "在庫", "数量", "カウント", "残数", "入出庫"],
    examples: ["棚卸し資料", "在庫カウント", "数量確認"],
  },
  {
    key: "work_shipping_packaging",
    emoji: "📮",
    label: "発送",
    description: "発送、梱包、出荷、配送、送付、送り状。",
    keywords: ["発送", "梱包", "出荷", "配送", "送付", "送り状"],
    examples: ["資料送付", "発送準備", "出荷確認"],
  },
  {
    key: "work_receiving",
    emoji: "📥",
    label: "受入",
    description: "受入、入荷、受領、到着、検収。",
    keywords: ["受入", "入荷", "受領", "到着", "検収"],
    examples: ["部材受入", "入荷確認", "検収する"],
  },
  {
    key: "work_deadline_submit",
    emoji: "📤",
    label: "提出",
    description: "提出、締切、期限、申請、送付、報告。",
    keywords: ["提出", "締切", "期限", "申請", "送付", "報告"],
    examples: ["休暇予定提出", "報告書提出", "申請期限"],
  },
  {
    key: "dev_nextjs",
    emoji: "▲",
    label: "Next.js",
    description: "Next.js、React、API Route、PWA実装。",
    keywords: ["Next.js", "React", "API Route", "PWA", "page.tsx"],
    examples: ["Next.js実装", "API Route修正", "page.tsx分割"],
  },
  {
    key: "dev_vercel",
    emoji: "▲",
    label: "Vercel",
    description: "Vercel、デプロイ、環境変数、Production、ビルド。",
    keywords: ["Vercel", "デプロイ", "環境変数", "Production", "ビルド"],
    examples: ["Vercelにデプロイ", "環境変数登録", "buildエラー"],
  },
  {
    key: "dev_google_drive",
    emoji: "🟢",
    label: "Drive API",
    description: "Google Drive API、Drive同期、OAuth、フォルダ保存。",
    keywords: ["Google Drive API", "Drive同期", "OAuth", "フォルダ", "manifest"],
    examples: ["Google Drive保存領域変更", "Drive同期最適化"],
  },
  {
    key: "dev_blob",
    emoji: "🟣",
    label: "Blob",
    description: "Vercel Blob、Blob Store、画像保存、public/private。",
    keywords: ["Vercel Blob", "Blob Store", "public", "private", "画像保存"],
    examples: ["Blob同期失敗", "private store", "画像バックアップ"],
  },
  {
    key: "dev_indexeddb",
    emoji: "🗄️",
    label: "IndexedDB",
    description: "IndexedDB、ローカルDB、IDBTransaction、キャッシュ。",
    keywords: ["IndexedDB", "ローカルDB", "IDBTransaction", "キャッシュ", "local"],
    examples: ["IDBTransactionエラー", "ローカルDB復元", "IndexedDB保存"],
  },
  {
    key: "dev_oauth",
    emoji: "🔑",
    label: "OAuth",
    description: "OAuth、認証、token、scope、refresh token。",
    keywords: ["OAuth", "認証", "token", "scope", "refresh token"],
    examples: ["Google OAuth設定", "drive.file scope", "認証失敗"],
  },
  {
    key: "dev_api_route",
    emoji: "🔌",
    label: "API",
    description: "API Route、Webhook、HTTP、POST、JSONレスポンス。",
    keywords: ["API Route", "Webhook", "HTTP", "POST", "JSON"],
    examples: ["shortcut webhook", "analyze-image API", "backup API"],
  },
  {
    key: "dev_webhook",
    emoji: "🪝",
    label: "Webhook",
    description: "Webhook、ショートカット、外部入力、自動登録。",
    keywords: ["Webhook", "ショートカット", "外部入力", "自動登録"],
    examples: ["iPhoneショートカットから登録", "Webhookテスト"],
  },
  {
    key: "dev_shortcut",
    emoji: "⚡",
    label: "Shortcut",
    description: "iOSショートカット、URLの内容を取得、Webhook呼び出し。",
    keywords: ["ショートカット", "iOS", "URLの内容を取得", "Webhook"],
    examples: ["ショートカット作成", "confirmationText通知"],
  },
  {
    key: "dev_embedding",
    emoji: "🧬",
    label: "Embedding",
    description: "embedding、意味検索、ベクトル、類似度、cosine。",
    keywords: ["embedding", "意味検索", "ベクトル", "類似度", "cosine"],
    examples: ["意味検索インデックス", "semantic icon embedding", "類似メモ提案"],
  },
  {
    key: "dev_prompt",
    emoji: "🧾",
    label: "Prompt",
    description: "プロンプト、AI方針、JSON出力、分類ルール。",
    keywords: ["プロンプト", "AI方針", "JSON", "分類", "Prompt"],
    examples: ["AIプロンプト編集", "action分類プロンプト", "日時抽出"],
  },
  {
    key: "dev_vision",
    emoji: "👁️",
    label: "Vision",
    description: "画像解析、Vision、写真AI、OCR、visible text。",
    keywords: ["画像解析", "Vision", "写真AI", "OCR", "visible text"],
    examples: ["写真解析", "画像タグ", "再解析ボタン"],
  },
  {
    key: "dev_ui_mobile",
    emoji: "📲",
    label: "モバイルUI",
    description: "スマホUI、PWA、タブバー、モーダル、レスポンシブ。",
    keywords: ["スマホUI", "PWA", "タブバー", "モーダル", "レスポンシブ"],
    examples: ["iPhoneレイアウト調整", "固定タブバー", "キーボード拡大"],
  },
  {
    key: "dev_dark_mode",
    emoji: "🌗",
    label: "Theme",
    description: "ダークモード、ライトモード、テーマ、色変数。",
    keywords: ["ダークモード", "ライトモード", "テーマ", "色変数"],
    examples: ["Light/Dark/System対応", "テーマ設定"],
  },
  {
    key: "dev_performance",
    emoji: "🏎️",
    label: "高速化",
    description: "パフォーマンス、遅い、並列化、計測、最適化。",
    keywords: ["パフォーマンス", "遅い", "並列化", "計測", "最適化"],
    examples: ["Webhookが10秒以上", "同期が遅い", "checksum差分スキップ"],
  },
  {
    key: "dev_refactor",
    emoji: "🧱",
    label: "分割",
    description: "リファクタ、分割、コンポーネント化、肥大化解消。",
    keywords: ["リファクタ", "分割", "コンポーネント化", "肥大化"],
    examples: ["page.tsx分割", "Settings分離", "Compose分離"],
  },
  {
    key: "dev_build_deploy",
    emoji: "🚀",
    label: "Deploy",
    description: "ビルド、デプロイ、push、Production、更新確認。",
    keywords: ["ビルド", "デプロイ", "push", "Production", "更新"],
    examples: ["git pushでVercelデプロイ", "PWA更新ボタン"],
  },
  {
    key: "dev_github",
    emoji: "🐙",
    label: "GitHub",
    description: "GitHub、commit、push、branch、repository。",
    keywords: ["GitHub", "commit", "push", "branch", "repository"],
    examples: ["GitHub連携", "commit to main", "push失敗"],
  },
  {
    key: "dev_error_log",
    emoji: "🧯",
    label: "ログ",
    description: "ログ、エラー、デバッグ、レポート、調査。",
    keywords: ["ログ", "エラー", "デバッグ", "レポート", "調査"],
    examples: ["Webhookテストモード", "同期レポート", "consoleログ"],
  },
  {
    key: "data_backup",
    emoji: "💾",
    label: "バックアップ",
    description: "バックアップ、保存、同期、アップロード、冗長化。",
    keywords: ["バックアップ", "保存", "同期", "アップロード", "冗長化"],
    examples: ["今すぐバックアップ", "全件再同期", "Google Driveへ保存"],
  },
  {
    key: "data_restore",
    emoji: "♻️",
    label: "復元",
    description: "復元、読み込み、ダウンロード、再取得、再構築。",
    keywords: ["復元", "読み込み", "ダウンロード", "再取得", "再構築"],
    examples: ["Driveから復元", "画像を再取得", "index再構築"],
  },
  {
    key: "data_import_zip",
    emoji: "🗜️",
    label: "ZIP",
    description: "zip、インポート、Scriptable移行、まとめ取り込み。",
    keywords: ["zip", "インポート", "Scriptable", "移行", "取り込み"],
    examples: ["50個ほどzipでアップロード", "Scriptable record移行"],
  },
  {
    key: "data_delete_tombstone",
    emoji: "🪦",
    label: "削除同期",
    description: "tombstone、削除同期、復活防止、delete marker。",
    keywords: ["tombstone", "削除同期", "復活防止", "delete marker"],
    examples: ["Drive tombstone", "削除したメモが戻る問題"],
  },
  {
    key: "data_manifest",
    emoji: "🗂️",
    label: "Manifest",
    description: "manifest、index、一覧、メタデータ、同期状態。",
    keywords: ["manifest", "index", "一覧", "メタデータ", "同期状態"],
    examples: ["manifest.json更新", "Drive上の一覧", "index扱い"],
  },
  {
    key: "data_sync_conflict",
    emoji: "⚔️",
    label: "競合",
    description: "競合、conflict、差分、上書き、マージ。",
    keywords: ["競合", "conflict", "差分", "上書き", "マージ"],
    examples: ["複数端末の同期競合", "差分取り込み", "上書き防止"],
  },
  {
    key: "calendar_event",
    emoji: "📅",
    label: "予定",
    description: "予定、calendar、イベント、日時指定、終日。",
    keywords: ["予定", "calendar", "イベント", "日時指定", "終日"],
    examples: ["Google Calendarへ登録", "今日の予定", "終日予定"],
  },
  {
    key: "reminder_done",
    emoji: "✅",
    label: "完了",
    description: "完了、done、タスク終了、チェック済み、済み。",
    keywords: ["完了", "done", "終了", "チェック済み", "済み"],
    examples: ["完了にする", "Google Tasks done", "タスク完了"],
  },
  {
    key: "reminder_overdue",
    emoji: "🔥",
    label: "期限超過",
    description: "期限超過、遅れ、未完了、持ち越し、overdue。",
    keywords: ["期限超過", "遅れ", "未完了", "持ち越し", "overdue"],
    examples: ["Carry-over", "古い未完了タスク", "期限を過ぎたタスク"],
  },
  {
    key: "daily_today",
    emoji: "☀️",
    label: "Today",
    description: "今日、Today、今日の作業台、次の行動、日次。",
    keywords: ["今日", "Today", "今日の作業台", "次の行動", "日次"],
    examples: ["Today View", "今日は何したらいい", "Next Action"],
  },
  {
    key: "weekly_view",
    emoji: "📆",
    label: "Week",
    description: "Weekly View、週次、週の俯瞰、ミニマップ。",
    keywords: ["Weekly View", "週次", "週", "俯瞰", "ミニマップ"],
    examples: ["Weekly Minimap", "週次ログビュー", "Weekタブ"],
  },
  {
    key: "settings_prompt",
    emoji: "🧠",
    label: "AI設定",
    description: "AI設定、プロンプト編集、モデル、閾値、辞書。",
    keywords: ["AI設定", "プロンプト編集", "モデル", "閾値", "辞書"],
    examples: ["Prompt設定モーダル", "Semantic Icon辞書", "意味検索設定"],
  },
  {
    key: "settings_sync",
    emoji: "🔁",
    label: "同期設定",
    description: "同期設定、範囲、除外、Google Tasks、Calendar。",
    keywords: ["同期設定", "範囲", "除外", "Google Tasks", "Calendar"],
    examples: ["同期レンジ設定", "完了済みタスク除外", "Calendar更新確認"],
  },
  {
    key: "search_semantic",
    emoji: "🧭",
    label: "意味検索",
    description: "意味検索、関連メモ、類似、Top10、閾値。",
    keywords: ["意味検索", "関連メモ", "類似", "Top10", "閾値"],
    examples: ["こんなの関連しませんか", "意味検索結果", "類似度設定"],
  },
  {
    key: "search_filter",
    emoji: "🔘",
    label: "フィルター",
    description: "フィルター、domain、action、PARA、タグ、絞り込み。",
    keywords: ["フィルター", "domain", "action", "PARA", "タグ", "絞り込み"],
    examples: ["domainワンタップフィルター", "Sort日本語化", "タグ検索"],
  },
  {
    key: "image_receipt",
    emoji: "🧾",
    label: "領収書",
    description: "領収書、レシート、予約票、紙の写真、伝票。",
    keywords: ["領収書", "レシート", "予約票", "伝票", "紙"],
    examples: ["眼科予約票", "領収書写真", "紙のメモを撮影"],
  },
  {
    key: "image_document",
    emoji: "📃",
    label: "文書画像",
    description: "文書画像、資料写真、紙資料、印刷物、書類。",
    keywords: ["文書画像", "資料写真", "紙資料", "印刷物", "書類"],
    examples: ["資料を写真で添付", "印刷物の画像", "書類画像解析"],
  },
  {
    key: "image_whiteboard",
    emoji: "⬜",
    label: "ホワイトボード",
    description: "ホワイトボード、板書、手書き、図、会議メモ。",
    keywords: ["ホワイトボード", "板書", "手書き", "図", "会議メモ"],
    examples: ["ホワイトボード写真", "手書きメモ", "図の記録"],
  },
  {
    key: "image_screenshot",
    emoji: "🖥️",
    label: "スクショ",
    description: "スクリーンショット、画面、UI、エラー画面、アプリ画像。",
    keywords: ["スクリーンショット", "画面", "UI", "エラー画面", "アプリ"],
    examples: ["Safari画面のスクショ", "エラー画面", "UI確認画像"],
  },
  {
    key: "image_product",
    emoji: "📷",
    label: "物撮り",
    description: "物、製品、部品、サンプル、外観写真。",
    keywords: ["物", "製品", "部品", "サンプル", "外観写真"],
    examples: ["サンプル写真", "部品画像", "外観写真"],
  },
  {
    key: "image_scene",
    emoji: "🌄",
    label: "風景",
    description: "風景、現場、場所、周囲、状況写真。",
    keywords: ["風景", "現場", "場所", "周囲", "状況写真"],
    examples: ["現場写真", "周囲の様子", "場所の記録"],
  },
  {
    key: "image_lightbox",
    emoji: "🔍",
    label: "拡大表示",
    description: "画像拡大、ライトボックス、サムネイル、高画質表示。",
    keywords: ["画像拡大", "ライトボックス", "サムネイル", "高画質"],
    examples: ["サムネをタップして高画質表示", "画像モーダル", "閉じるボタン"],
  },
  {
    key: "note_draft",
    emoji: "📝",
    label: "下書き",
    description: "下書き、未解析、あとでAI解析、Raw input。",
    keywords: ["下書き", "未解析", "あとでAI解析", "Raw input"],
    examples: ["下書きとして保存", "AI解析ボタン", "書きかけメモ"],
  },
  {
    key: "note_idea",
    emoji: "💡",
    label: "アイデア",
    description: "アイデア、思いつき、改善案、構想、仮説。",
    keywords: ["アイデア", "思いつき", "改善案", "構想", "仮説"],
    examples: ["UI改善アイデア", "新機能案", "仮説メモ"],
  },
  {
    key: "note_journal",
    emoji: "📓",
    label: "日記",
    description: "日記、ログ、記録、振り返り、今日のメモ。",
    keywords: ["日記", "ログ", "記録", "振り返り", "今日のメモ"],
    examples: ["今日の作業ログ", "振り返り", "日々の記録"],
  },
  {
    key: "note_reference",
    emoji: "🔖",
    label: "参考",
    description: "参考情報、資料、リンク、知識、保存したい情報。",
    keywords: ["参考情報", "資料", "リンク", "知識", "保存"],
    examples: ["参考リンク", "知識メモ", "資料の要点"],
  },
  {
    key: "note_decision",
    emoji: "✅",
    label: "決定",
    description: "決定事項、方針、合意、選択、判断。",
    keywords: ["決定事項", "方針", "合意", "選択", "判断"],
    examples: ["方針を決定", "合意事項", "判断メモ"],
  },
  {
    key: "note_question",
    emoji: "❓",
    label: "質問",
    description: "質問、疑問、確認したいこと、わからないこと。",
    keywords: ["質問", "疑問", "確認したい", "わからない", "なぜ"],
    examples: ["なぜだと思う", "確認したい点", "疑問メモ"],
  },
  {
    key: "note_summary",
    emoji: "🧾",
    label: "要約",
    description: "要約、まとめ、整理、箇条書き、概要。",
    keywords: ["要約", "まとめ", "整理", "箇条書き", "概要"],
    examples: ["議事録まとめ", "資料要約", "概要整理"],
  },
  {
    key: "comm_line_chat",
    emoji: "💬",
    label: "チャット",
    description: "チャット、LINE、メッセージ、会話、DM。",
    keywords: ["チャット", "LINE", "メッセージ", "会話", "DM"],
    examples: ["LINEで連絡", "チャット返信", "メッセージ確認"],
  },
  {
    key: "comm_phone",
    emoji: "☎️",
    label: "電話",
    description: "電話、通話、折り返し、連絡先、着信。",
    keywords: ["電話", "通話", "折り返し", "連絡先", "着信"],
    examples: ["電話する", "折り返し連絡", "通話メモ"],
  },
  {
    key: "comm_thanks",
    emoji: "🙏",
    label: "お礼",
    description: "お礼、感謝、返礼、ありがとう、挨拶。",
    keywords: ["お礼", "感謝", "返礼", "ありがとう", "挨拶"],
    examples: ["お礼メール", "感謝を伝える", "挨拶連絡"],
  },
  {
    key: "family_parent",
    emoji: "👨‍👩‍👧‍👦",
    label: "家族",
    description: "家族、親、子供、家庭内の相談、予定共有。",
    keywords: ["家族", "親", "子供", "家庭", "予定共有"],
    examples: ["家族の予定確認", "家庭内相談", "子供の予定"],
  },
  {
    key: "family_kumiko",
    emoji: "👩",
    label: "久美子",
    description: "久美子さん、家族、予定、連絡、許可確認。",
    keywords: ["久美子", "久美子さん"],
    examples: ["久美子へヘアカットの予定", "久美子にシルバニアをあげる"],
  },
  {
    key: "family_rin",
    emoji: "👧",
    label: "凜",
    description: "凜ちゃん、英語、ピアノ、学校、習い事。",
    keywords: ["凜", "凜ちゃん", "英語", "ピアノ"],
    examples: ["凜ちゃんピアノ練習", "凜ちゃんの英語継続"],
  },
  {
    key: "family_eto",
    emoji: "👦",
    label: "瑛",
    description: "瑛ちゃん、瑛登、眼科、子供予定、診察。",
    keywords: ["瑛", "瑛ちゃん", "瑛登"],
    examples: ["瑛ちゃん眼科予定", "瑛登の予定"],
  },
  {
    key: "family_school_event",
    emoji: "🎪",
    label: "学校行事",
    description: "学校行事、PTA、運動会、発表会、保護者会。",
    keywords: ["学校行事", "PTA", "運動会", "発表会", "保護者会"],
    examples: ["PTA議事録作成", "学校行事予定", "保護者会"],
  },
  {
    key: "family_holiday",
    emoji: "🏖️",
    label: "家族休日",
    description: "家族の休日、外出、旅行、遊び、休み。",
    keywords: ["家族の休日", "外出", "旅行", "遊び", "休み"],
    examples: ["家族で外出", "休日の予定", "長野旅行計画"],
  },
  {
    key: "pet_care",
    emoji: "🐶",
    label: "ペット",
    description: "ペット、世話、餌、動物病院、飼育。",
    keywords: ["ペット", "世話", "餌", "動物病院", "飼育"],
    examples: ["ペットの世話", "餌を買う", "動物病院"],
  },
  {
    key: "outdoor_garden",
    emoji: "🌱",
    label: "庭",
    description: "庭、植物、外作業、草、家庭菜園。",
    keywords: ["庭", "植物", "外作業", "草", "家庭菜園"],
    examples: ["庭の草取り", "植物の世話", "外作業"],
  },
  {
    key: "hobby_game",
    emoji: "🎮",
    label: "ゲーム",
    description: "ゲーム、遊び、娯楽、アプリ、趣味。",
    keywords: ["ゲーム", "遊び", "娯楽", "アプリ", "趣味"],
    examples: ["ゲームのメモ", "趣味の予定", "アプリ確認"],
  },
  {
    key: "hobby_movie",
    emoji: "🎬",
    label: "映画",
    description: "映画、動画、配信、ドラマ、視聴。",
    keywords: ["映画", "動画", "配信", "ドラマ", "視聴"],
    examples: ["映画を見る", "動画メモ", "配信確認"],
  },
  {
    key: "hobby_reading",
    emoji: "📚",
    label: "読書趣味",
    description: "読書、本、漫画、記事、読みたいもの。",
    keywords: ["読書", "本", "漫画", "記事", "読みたい"],
    examples: ["本を読む", "漫画メモ", "読みたい記事"],
  },
  {
    key: "hobby_music",
    emoji: "🎧",
    label: "音楽趣味",
    description: "音楽、聴く、曲、ライブ、演奏。",
    keywords: ["音楽", "聴く", "曲", "ライブ", "演奏"],
    examples: ["音楽を聴く", "ライブ予定", "曲メモ"],
  },
  {
    key: "personal_goal",
    emoji: "🎯",
    label: "目標",
    description: "目標、習慣、改善、継続、自己管理。",
    keywords: ["目標", "習慣", "改善", "継続", "自己管理"],
    examples: ["英語継続", "習慣化", "目標管理"],
  },
  {
    key: "admin_application",
    emoji: "📮",
    label: "申請",
    description: "申請、届け出、書類提出、手続き、役所。",
    keywords: ["申請", "届け出", "書類提出", "手続き", "役所"],
    examples: ["休暇予定提出", "申請書確認", "手続きする"],
  },
  {
    key: "admin_reservation",
    emoji: "📅",
    label: "予約",
    description: "予約、予約確認、予約票、日時、受付。",
    keywords: ["予約", "予約確認", "予約票", "日時", "受付"],
    examples: ["歯医者の予約", "眼科予約票", "予約詳細確認"],
  },
  {
    key: "admin_license",
    emoji: "🪪",
    label: "証明",
    description: "免許、証明書、保険証、身分証、カード。",
    keywords: ["免許", "証明書", "保険証", "身分証", "カード"],
    examples: ["保険証確認", "免許更新", "身分証準備"],
  },
  {
    key: "admin_password",
    emoji: "🔐",
    label: "パスワード",
    description: "パスワード、ログイン、アカウント、認証、2FA。",
    keywords: ["パスワード", "ログイン", "アカウント", "認証", "2FA"],
    examples: ["ログインできない", "アカウント確認", "2FA設定"],
  },
  {
    key: "admin_subscription",
    emoji: "🔁",
    label: "サブスク",
    description: "サブスク、契約、更新、解約、月額。",
    keywords: ["サブスク", "契約", "更新", "解約", "月額"],
    examples: ["サブスク解約", "契約更新", "月額費用確認"],
  },
  {
    key: "admin_address",
    emoji: "🏷️",
    label: "住所",
    description: "住所、宛先、配送先、連絡先、所在地。",
    keywords: ["住所", "宛先", "配送先", "連絡先", "所在地"],
    examples: ["住所変更", "配送先確認", "宛先を調べる"],
  },
  {
    key: "emergency",
    emoji: "🚨",
    label: "緊急",
    description: "緊急、至急、急ぎ、今すぐ、重要、トラブル。",
    keywords: ["緊急", "至急", "急ぎ", "今すぐ", "重要", "トラブル"],
    examples: ["至急対応", "緊急連絡", "重要タスク"],
  },
  {
    key: "unknown_question",
    emoji: "❔",
    label: "未整理",
    description: "未整理、未確定、不明、あとで確認、判断待ち。",
    keywords: ["未整理", "未確定", "不明", "あとで確認", "判断待ち"],
    examples: ["未特定のメモ", "あとで確認", "内容不明"],
  },
];

function createExtendedSemanticIconEntries() {
  return EXTENDED_SEMANTIC_ICON_SEEDS.map(createEntry);
}

export function createDefaultSemanticIconDictionary(): CGMPSemanticIconEntry[] {
  const base: CGMPSemanticIconEntry[] = [
    {
      key: "medical_dental",
      emoji: "🦷",
      label: "歯科",
      description: "歯医者、歯科、予約票、通院、デンタルケア。",
      keywords: ["歯医者", "歯科", "デンタル", "通院", "予約票"],
      examples: ["歯医者の予約", "歯科検診", "眼科予約票の確認"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "medical_hospital",
      emoji: "🏥",
      label: "医療",
      description: "病院、眼科、耳鼻科、薬、健康診断、医療関連の予定や記録。",
      keywords: ["病院", "眼科", "耳鼻科", "薬", "健康診断"],
      examples: ["眼科検査の予約詳細", "薬を受け取りに行く", "健康診断の結果確認"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "meeting",
      emoji: "👥",
      label: "会議",
      description: "会議、打ち合わせ、ミーティング、1on1、関係者との相談。",
      keywords: ["会議", "打合せ", "打ち合わせ", "ミーティング", "1on1", "相談"],
      examples: ["DNP様打ち合わせ", "森部長代理提案の傷検証資料確認", "矢田さんと磯本さんのコミュニケーション確認"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "communication",
      emoji: "💬",
      label: "連絡",
      description: "メール、電話、返信、送付、連絡、確認依頼。",
      keywords: ["メール", "電話", "返信", "送信", "送付", "連絡"],
      examples: ["小林のメールとDNPの状況整理", "棚卸し資料の西尾さんへの送付", "前田さんへ連絡"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "document",
      emoji: "📄",
      label: "資料",
      description: "資料、文書、レポート、議事録、報告書、仕様書。",
      keywords: ["資料", "文書", "レポート", "議事録", "報告書", "仕様書"],
      examples: ["品質ISO進捗記入", "PSC案件報告書確認", "資料準備"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "review_check",
      emoji: "🔍",
      label: "確認",
      description: "確認、レビュー、チェック、検証、調査、点検。",
      keywords: ["確認", "レビュー", "チェック", "検証", "調査", "点検"],
      examples: ["表面不良確認", "仕様確認", "Google Driveバックアップ確認"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "plan_strategy",
      emoji: "🧭",
      label: "計画",
      description: "計画、方針、整理、段取り、スケジュール設計、目標。",
      keywords: ["計画", "方針", "整理", "段取り", "目標", "予定"],
      examples: ["夏休み長野旅行計画の確定目標", "台風対策の確認", "今後の対応打ち合わせ"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "travel",
      emoji: "🧳",
      label: "旅行",
      description: "旅行、出張、ホテル、旅程、移動、予約。",
      keywords: ["旅行", "出張", "ホテル", "旅程", "移動", "予約"],
      examples: ["山城出張の報告督促", "長野旅行計画", "ホテル予約確認"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "shopping",
      emoji: "🛒",
      label: "買物",
      description: "購入、買い物、発注、準備物、日用品。",
      keywords: ["買う", "購入", "買い物", "発注", "準備"],
      examples: ["子供の自転車購入", "ホットケーキミックス購入", "財布と車の鍵の準備"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "finance",
      emoji: "💳",
      label: "お金",
      description: "支払い、精算、請求、費用、原価、経費、カード。",
      keywords: ["支払い", "精算", "請求", "費用", "原価", "経費", "カード"],
      examples: ["経理セミナー原価計算", "労務費資料送付", "支払い確認"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "family_child",
      emoji: "🧒",
      label: "子供",
      description: "子供、家族、学校、宿題、習い事、凜、瑛登。",
      keywords: ["子供", "家族", "学校", "宿題", "習い事", "凜", "瑛登"],
      examples: ["凜ちゃんの英語継続について", "久美子にシルバニアあげる予定", "子供の自転車購入"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "food",
      emoji: "🍽️",
      label: "食事",
      description: "食事、ご飯、弁当、ランチ、買い出し、献立、料理、レシピ。",
      keywords: ["食事", "ご飯", "弁当", "ランチ", "買い出し", "献立", "料理", "レシピ", "ピザ"],
      examples: ["晩御飯買い出し", "ランチ予定", "弁当準備", "酒蒸しハンバーグのレシピ"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "engineering",
      emoji: "💻",
      label: "開発",
      description: "実装、コード、PWA、Next.js、Vercel、Scriptable、Codex。",
      keywords: ["実装", "コード", "PWA", "Next.js", "Vercel", "Scriptable", "Codex"],
      examples: ["CGMP PWAのUI修正", "Webhookテスト", "Embedding検索機能"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "experiment_inspection",
      emoji: "🧪",
      label: "検査",
      description: "検査、試験、評価、実験、サンプル、測定、ISO。",
      keywords: ["検査", "試験", "評価", "実験", "サンプル", "測定", "ISO"],
      examples: ["X3サンプル表面不良確認", "NA3検査機サポート待機予定", "品質ISO進捗記入"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "factory",
      emoji: "🏭",
      label: "現場",
      description: "工場、生産、設備、現場、ライン、製造、加工。",
      keywords: ["工場", "生産", "設備", "現場", "ライン", "製造", "加工"],
      examples: ["AMAT向け生産キャパと納入スケジュール", "薄膜PSC試作の進め方", "設備仕様検討"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "delivery",
      emoji: "📦",
      label: "納入",
      description: "出荷、梱包、物流、納入、配送、送付。",
      keywords: ["出荷", "梱包", "物流", "納入", "配送", "送付"],
      examples: ["納入スケジュール確認", "棚卸し資料の送付", "出荷準備"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "deadline",
      emoji: "⏰",
      label: "期限",
      description: "締切、期限、督促、リマインド、提出。",
      keywords: ["締切", "期限", "督促", "リマインド", "提出"],
      examples: ["6/3の休暇予定提出", "報告督促", "資料提出期限"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "calendar_schedule",
      emoji: "📆",
      label: "日程",
      description: "日程、予定、スケジュール、予約、時間枠、カレンダー登録。",
      keywords: ["日程", "予定", "スケジュール", "予約", "時間枠", "カレンダー"],
      examples: ["6月2日の予定確認", "会議日程を登録", "予約時間の確認"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "task_todo",
      emoji: "☑️",
      label: "Todo",
      description: "タスク、やること、Todo、リマインダー、未完了作業。",
      keywords: ["タスク", "やること", "Todo", "リマインダー", "未完了"],
      examples: ["明日のタスク", "資料確認Todo", "完了にする"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "automation_sync",
      emoji: "🔄",
      label: "同期",
      description: "同期、バックアップ、アップロード、ダウンロード、復元、反映。",
      keywords: ["同期", "バックアップ", "アップロード", "ダウンロード", "復元", "反映"],
      examples: ["Google Drive同期確認", "Blobから復元", "全件再同期"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "cloud_drive",
      emoji: "☁️",
      label: "クラウド",
      description: "Google Drive、Vercel Blob、クラウド保存、オンラインストレージ。",
      keywords: ["Google Drive", "Drive", "Vercel Blob", "Blob", "クラウド", "保存先"],
      examples: ["Drive保存領域を変更", "Vercel Blob同期", "クラウドバックアップ"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "phone_shortcut",
      emoji: "📱",
      label: "iPhone",
      description: "iPhone、ショートカット、PWA、Safari、ホーム画面、モバイル操作。",
      keywords: ["iPhone", "ショートカット", "PWA", "Safari", "ホーム画面", "モバイル"],
      examples: ["iOS Shortcut webhook", "ホーム画面PWA更新", "iPhoneで写真追加"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "ai_prompt",
      emoji: "🤖",
      label: "AI",
      description: "AI解析、プロンプト、embedding、意味検索、画像解析。",
      keywords: ["AI", "プロンプト", "embedding", "意味検索", "画像解析", "OpenAI"],
      examples: ["AIプロンプト編集", "semantic icon辞書", "画像AI解析"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "search_find",
      emoji: "🔎",
      label: "検索",
      description: "検索、フィルター、絞り込み、一覧、見つける、探す。",
      keywords: ["検索", "フィルター", "絞り込み", "一覧", "探す", "見つける"],
      examples: ["domainフィルター", "意味検索", "タグ検索"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "bug_fix",
      emoji: "🐞",
      label: "不具合",
      description: "バグ、不具合、エラー、失敗、修正、原因調査。",
      keywords: ["バグ", "不具合", "エラー", "失敗", "修正", "原因"],
      examples: ["削除時のIndexedDBエラー", "同期が失敗", "表示崩れ修正"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "ui_design",
      emoji: "🎨",
      label: "UI",
      description: "UI、デザイン、レイアウト、見た目、モーダル、アニメーション。",
      keywords: ["UI", "デザイン", "レイアウト", "モーダル", "アニメーション", "見た目"],
      examples: ["Today viewのUI調整", "カードの余白", "ミニマップ表示"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "settings_config",
      emoji: "⚙️",
      label: "設定",
      description: "設定、環境変数、Preferences、テーマ、閾値、構成変更。",
      keywords: ["設定", "環境変数", "テーマ", "閾値", "構成", "Preferences"],
      examples: ["Settings画面整理", "semantic icon閾値", "環境変数追加"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "import_export",
      emoji: "📥",
      label: "移行",
      description: "インポート、エクスポート、移行、zip、Scriptableデータ取り込み。",
      keywords: ["インポート", "エクスポート", "移行", "zip", "Scriptable", "取り込み"],
      examples: ["Scriptableログ移行", "zipアップロード", "データ移行"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "delete_archive",
      emoji: "🗑️",
      label: "削除",
      description: "削除、アーカイブ、tombstone、消す、復活防止。",
      keywords: ["削除", "アーカイブ", "tombstone", "消す", "復活", "全削除"],
      examples: ["メモ削除の挙動", "Drive tombstone", "選択削除"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "backup_restore",
      emoji: "🧰",
      label: "保守",
      description: "保守、復元、再構築、リカバリ、バックアップ検証。",
      keywords: ["保守", "復元", "再構築", "リカバリ", "検証", "復旧"],
      examples: ["画像復元", "index再構築", "Drive実在確認"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "weather_disaster",
      emoji: "🌪️",
      label: "災害",
      description: "台風、雨、雪、災害、停電、防災、天気。",
      keywords: ["台風", "雨", "雪", "災害", "停電", "防災", "天気"],
      examples: ["台風対策の確認", "雪国だった", "天気の影響確認"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "car_transport",
      emoji: "🚗",
      label: "移動",
      description: "車、電車、交通、移動、駐車場、運転、充電。",
      keywords: ["車", "電車", "交通", "移動", "駐車場", "運転", "充電"],
      examples: ["電気自動車充電ケーブル", "車の鍵", "移動予定"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "home_house",
      emoji: "🏠",
      label: "家庭",
      description: "家、家庭、住まい、家事、生活、家族内の用事。",
      keywords: ["家", "家庭", "住まい", "家事", "生活", "自宅"],
      examples: ["家の片付け", "家庭の予定", "生活管理"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "cleaning",
      emoji: "🧹",
      label: "掃除",
      description: "掃除、片付け、整理整頓、ゴミ、清掃。",
      keywords: ["掃除", "片付け", "整理整頓", "ゴミ", "清掃"],
      examples: ["外ゴミ階段", "片付ける", "掃除予定"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "clothes_laundry",
      emoji: "👕",
      label: "衣類",
      description: "服、洗濯、衣類、サイズ、靴、身支度。",
      keywords: ["服", "洗濯", "衣類", "サイズ", "靴", "身支度"],
      examples: ["サイズ140cmの服", "洗濯", "服の購入計画"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "pet_animal",
      emoji: "🐾",
      label: "動物",
      description: "ペット、動物、生き物、魚、飼育、観察。",
      keywords: ["ペット", "動物", "生き物", "魚", "飼育", "観察"],
      examples: ["手に乗った生き物の写真", "魚の世話", "動物観察"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "education_learning",
      emoji: "📚",
      label: "学習",
      description: "学習、勉強、英語、セミナー、講座、教育。",
      keywords: ["学習", "勉強", "英語", "セミナー", "講座", "教育"],
      examples: ["凜ちゃんの英語継続", "経理セミナー", "学習計画"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "book_reading",
      emoji: "📖",
      label: "読書",
      description: "本、読書、資料読み、参考文献、記事。",
      keywords: ["本", "読書", "参考文献", "記事", "読み物"],
      examples: ["参考資料を読む", "記事確認", "本のメモ"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "legal_contract",
      emoji: "📝",
      label: "契約",
      description: "契約、規約、許可、申請、承認、法務系の確認。",
      keywords: ["契約", "規約", "許可", "申請", "承認", "法務"],
      examples: ["シルバニアをあげる許可", "申請書確認", "承認事項"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "security_password",
      emoji: "🔐",
      label: "認証",
      description: "認証、ログイン、OAuth、token、API key、権限。",
      keywords: ["認証", "ログイン", "OAuth", "token", "API key", "権限"],
      examples: ["Google OAuth設定", "Webhook token", "環境変数登録"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "energy_electricity",
      emoji: "🔌",
      label: "電気",
      description: "電気、充電、電源、ケーブル、バッテリー、設備電源。",
      keywords: ["電気", "充電", "電源", "ケーブル", "バッテリー", "EV"],
      examples: ["電気自動車充電ケーブル", "電源確認", "バッテリー"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "measurement_size",
      emoji: "📏",
      label: "寸法",
      description: "サイズ、寸法、測定、長さ、厚み、mm、座標。",
      keywords: ["サイズ", "寸法", "測定", "長さ", "厚み", "mm", "座標"],
      examples: ["72.5-120mmガラス基板サイズ", "二次元座標測定器", "15x2セット"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "material_glass",
      emoji: "🧊",
      label: "材料",
      description: "ガラス、薄膜、基板、材料、サンプル、表面。",
      keywords: ["ガラス", "薄膜", "基板", "材料", "サンプル", "表面"],
      examples: ["DNPガラスサイズ", "薄膜PSC", "X3サンプル表面不良"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "customer_sales",
      emoji: "🤝",
      label: "顧客",
      description: "顧客、取引先、先方、営業、依頼、提案。",
      keywords: ["顧客", "取引先", "先方", "営業", "依頼", "提案"],
      examples: ["DNP様打ち合わせ", "AMAT向け", "お客様への伝達"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "quality_iso",
      emoji: "🏷️",
      label: "品質",
      description: "品質、ISO、不良、検査結果、是正、監査。",
      keywords: ["品質", "ISO", "不良", "検査結果", "是正", "監査"],
      examples: ["品質ISO進捗記入", "表面不良確認", "品質報告"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "procurement",
      emoji: "🧾",
      label: "購買",
      description: "見積、購買、発注、請求書、領収書、伝票。",
      keywords: ["見積", "購買", "発注", "請求書", "領収書", "伝票"],
      examples: ["検査機見積もり作業", "発注準備", "領収書画像"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "maintenance_repair",
      emoji: "🛠️",
      label: "修理",
      description: "修理、メンテナンス、設備保全、調整、再起動、対応。",
      keywords: ["修理", "メンテナンス", "設備保全", "調整", "再起動", "対応"],
      examples: ["検査機の再起動ループ対策", "設備メンテ", "調整作業"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "inventory_stock",
      emoji: "📊",
      label: "在庫",
      description: "在庫、棚卸し、数量、入荷、出荷、残数。",
      keywords: ["在庫", "棚卸し", "数量", "入荷", "出荷", "残数"],
      examples: ["棚卸し資料", "30枚", "在庫確認"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "ticket_receipt",
      emoji: "🎫",
      label: "券",
      description: "予約票、チケット、領収書、レシート、受付票。",
      keywords: ["予約票", "チケット", "領収書", "レシート", "受付票"],
      examples: ["眼科検査の予約票", "領収書写真", "受付票確認"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "map_location",
      emoji: "📍",
      label: "場所",
      description: "場所、住所、訪問先、現地、地図、会場。",
      keywords: ["場所", "住所", "訪問先", "現地", "地図", "会場"],
      examples: ["訪問先確認", "会場の場所", "現地集合"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "event_ceremony",
      emoji: "🎉",
      label: "行事",
      description: "イベント、行事、式、発表会、記念日、参加予定。",
      keywords: ["イベント", "行事", "式", "発表会", "記念日", "参加"],
      examples: ["学校行事", "イベント参加", "発表会予定"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "rest_sleep",
      emoji: "🌙",
      label: "休息",
      description: "休み、休暇、睡眠、体調回復、夜、集中タイム。",
      keywords: ["休み", "休暇", "睡眠", "体調", "夜", "集中"],
      examples: ["6/3の休暇予定提出", "夜の集中タイム", "体調を整える"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "exercise_health",
      emoji: "🏃",
      label: "運動",
      description: "運動、散歩、トレーニング、体力、健康習慣。",
      keywords: ["運動", "散歩", "トレーニング", "体力", "健康習慣"],
      examples: ["散歩する", "運動予定", "体力づくり"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "garden_outdoor",
      emoji: "🌿",
      label: "屋外",
      description: "屋外、庭、外作業、自然、植物、外出先の観察。",
      keywords: ["屋外", "庭", "外作業", "自然", "植物", "外出"],
      examples: ["外での作業", "自然観察", "庭の確認"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "idea",
      emoji: "💡",
      label: "発想",
      description: "アイデア、構想、考える、改善案、発明、仮説。",
      keywords: ["アイデア", "構想", "考える", "改善", "仮説"],
      examples: ["UIの改善案", "プロンプト設計", "検索体験の改善"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "image_photo",
      emoji: "🖼️",
      label: "画像",
      description: "写真、スクリーンショット、画像、添付、カメラ、撮影。",
      keywords: ["写真", "スクリーンショット", "画像", "添付", "カメラ", "撮影"],
      examples: ["DNP様強化依頼詳細スクリーンショット", "写真を追加", "画面キャプチャ確認"],
      enabled: true,
      updated_at: now,
    },
  ];

  return [...base, ...createExtendedSemanticIconEntries()];
}
