import type { CGMPSemanticIconEntry } from "./types";

export const SEMANTIC_ICON_DICTIONARY_VERSION = "2026-06-07.1";
export const DEFAULT_SEMANTIC_ICON_THRESHOLD = 0.42;

const now = "2026-06-07T00:00:00.000Z";

export function createDefaultSemanticIconDictionary(): CGMPSemanticIconEntry[] {
  return [
    {
      key: "medical_dental",
      emoji: "🦷",
      label: "歯科",
      description: "歯医者、歯科、予約票、通院、デンタルケア。",
      keywords: ["歯医者", "歯科", "デンタル", "通院", "予約票"],
      examples: ["歯医者の予約", "歯科検診", "眼科予約票の確認"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "medical_hospital",
      emoji: "🏥",
      label: "医療",
      description: "病院、眼科、耳鼻科、薬、健康診断、医療関連の予定や記録。",
      keywords: ["病院", "眼科", "耳鼻科", "薬", "健康診断"],
      examples: ["眼科検査の予約詳細", "薬を受け取りに行く", "健康診断の結果確認"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "meeting",
      emoji: "👥",
      label: "会議",
      description: "会議、打ち合わせ、ミーティング、1on1、関係者との相談。",
      keywords: ["会議", "打合せ", "打ち合わせ", "ミーティング", "1on1", "相談"],
      examples: ["DNP様打ち合わせ", "森部長代理提案の傷検証資料確認", "矢田さんと磯本さんのコミュニケーション確認"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "communication",
      emoji: "💬",
      label: "連絡",
      description: "メール、電話、返信、送付、連絡、確認依頼。",
      keywords: ["メール", "電話", "返信", "送信", "送付", "連絡"],
      examples: ["小林のメールとDNPの状況整理", "棚卸し資料の西尾さんへの送付", "前田さんへ連絡"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "document",
      emoji: "📄",
      label: "資料",
      description: "資料、文書、レポート、議事録、報告書、仕様書。",
      keywords: ["資料", "文書", "レポート", "議事録", "報告書", "仕様書"],
      examples: ["品質ISO進捗記入", "PSC案件報告書確認", "資料準備"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "review_check",
      emoji: "🔍",
      label: "確認",
      description: "確認、レビュー、チェック、検証、調査、点検。",
      keywords: ["確認", "レビュー", "チェック", "検証", "調査", "点検"],
      examples: ["表面不良確認", "仕様確認", "Google Driveバックアップ確認"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "plan_strategy",
      emoji: "🧭",
      label: "計画",
      description: "計画、方針、整理、段取り、スケジュール設計、目標。",
      keywords: ["計画", "方針", "整理", "段取り", "目標", "予定"],
      examples: ["夏休み長野旅行計画の確定目標", "台風対策の確認", "今後の対応打ち合わせ"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "travel",
      emoji: "🧳",
      label: "旅行",
      description: "旅行、出張、ホテル、旅程、移動、予約。",
      keywords: ["旅行", "出張", "ホテル", "旅程", "移動", "予約"],
      examples: ["山城出張の報告督促", "長野旅行計画", "ホテル予約確認"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "shopping",
      emoji: "🛒",
      label: "買物",
      description: "購入、買い物、発注、準備物、日用品。",
      keywords: ["買う", "購入", "買い物", "発注", "準備"],
      examples: ["子供の自転車購入", "ホットケーキミックス購入", "財布と車の鍵の準備"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "finance",
      emoji: "💳",
      label: "お金",
      description: "支払い、精算、請求、費用、原価、経費、カード。",
      keywords: ["支払い", "精算", "請求", "費用", "原価", "経費", "カード"],
      examples: ["経理セミナー原価計算", "労務費資料送付", "支払い確認"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "family_child",
      emoji: "🧒",
      label: "子供",
      description: "子供、家族、学校、宿題、習い事、凜、瑛登。",
      keywords: ["子供", "家族", "学校", "宿題", "習い事", "凜", "瑛登"],
      examples: ["凜ちゃんの英語継続について", "久美子にシルバニアあげる予定", "子供の自転車購入"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "food",
      emoji: "🍽️",
      label: "食事",
      description: "食事、ご飯、弁当、ランチ、買い出し、献立。",
      keywords: ["食事", "ご飯", "弁当", "ランチ", "買い出し", "献立"],
      examples: ["晩御飯買い出し", "ランチ予定", "弁当準備"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "engineering",
      emoji: "💻",
      label: "開発",
      description: "実装、コード、PWA、Next.js、Vercel、Scriptable、Codex。",
      keywords: ["実装", "コード", "PWA", "Next.js", "Vercel", "Scriptable", "Codex"],
      examples: ["CGMP PWAのUI修正", "Webhookテスト", "Embedding検索機能"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "experiment_inspection",
      emoji: "🧪",
      label: "検査",
      description: "検査、試験、評価、実験、サンプル、測定、ISO。",
      keywords: ["検査", "試験", "評価", "実験", "サンプル", "測定", "ISO"],
      examples: ["X3サンプル表面不良確認", "NA3検査機サポート待機予定", "品質ISO進捗記入"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "factory",
      emoji: "🏭",
      label: "現場",
      description: "工場、生産、設備、現場、ライン、製造、加工。",
      keywords: ["工場", "生産", "設備", "現場", "ライン", "製造", "加工"],
      examples: ["AMAT向け生産キャパと納入スケジュール", "薄膜PSC試作の進め方", "設備仕様検討"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "delivery",
      emoji: "📦",
      label: "納入",
      description: "出荷、梱包、物流、納入、配送、送付。",
      keywords: ["出荷", "梱包", "物流", "納入", "配送", "送付"],
      examples: ["納入スケジュール確認", "棚卸し資料の送付", "出荷準備"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "deadline",
      emoji: "⏰",
      label: "期限",
      description: "締切、期限、督促、リマインド、提出。",
      keywords: ["締切", "期限", "督促", "リマインド", "提出"],
      examples: ["6/3の休暇予定提出", "報告督促", "資料提出期限"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "idea",
      emoji: "💡",
      label: "発想",
      description: "アイデア、構想、考える、改善案、発明、仮説。",
      keywords: ["アイデア", "構想", "考える", "改善", "仮説"],
      examples: ["UIの改善案", "プロンプト設計", "検索体験の改善"],
      enabled: true,
      updated_at: now,
    },
    {
      key: "image_photo",
      emoji: "🖼️",
      label: "画像",
      description: "写真、スクリーンショット、画像、添付、カメラ、撮影。",
      keywords: ["写真", "スクリーンショット", "画像", "添付", "カメラ", "撮影"],
      examples: ["DNP様強化依頼詳細スクリーンショット", "写真を追加", "画面キャプチャ確認"],
      enabled: true,
      updated_at: now,
    },
  ];
}
